### ISSUE TITLE
Are queries reactive to reactive variables?

### ISSUE THREAD

**Issue by serggiocaramello** [Diizzayy/nuxt-graphql-client#102]
Hello, i have to change the value of the variable limit to 5, but i dont know why the displayed result is always 10.

I would like to ask if is a way to change the amount of displayed resullt from 10 to 5.

    <template>
      <div>
        <h2>Starlink Launches</h2>
        <p>Limit: {{limit}}</p>
        <button @click="limit = 5">change limit to 5</button>

        <p v-for="(entry, i) of data?.launches" :key="entry.id">
      {{ i + 1 }}. Mission Name: {{ entry.mission_name }} ({{
        entry.launch_year
      }})
        </p>
      </div>
    </template>

    <script lang="ts" setup>
    const limit = ref(10)

    const { data } = await useAsyncData('starlink', () => GqlLaunches({limit: limit.value}))
    </script>

repo: https://github.com/serggiocaramello/nuxt-graphql-client-test

**Comment by Diizzayy** [comment]
@serggiocaramello Queries aren't reactive by default, however though using your example above, you can extract the `refresh` function from `useAsyncData` and either call it manually or use a watcher as seen below

```vue
<script lang="ts" setup>
const limit = ref(10)

const { data, refresh, pending } = await useAsyncData('starlink', () => GqlLaunches({ limit: limit.value }));

// automatically refresh whenever the limit changed
watch(limit, () => refresh())
</script>
```

**Comment by serggiocaramello** [comment]
@Diizzayy Thanks, it works!
