### ISSUE TITLE
ERROR  (node:22713)

### ISSUE THREAD

**Issue by b-arabah** [Diizzayy/nuxt-graphql-client#107]
Hello,

This error happens every time Nuxt starts (with yarn run dev). 

ERROR  (node:22713) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

Node v16.14.2

**Comment by Diizzayy** [comment]
@b-arabah This isn't an actual bug nor error for your app, but rather a warning that experimental NodeJS features are being used within your app or it's dependencies. I know the warnings are noisy but they can be safely ignored.
