### ISSUE TITLE
Unknown type error

### ISSUE THREAD

**Issue by yalondpsi** [Diizzayy/nuxt-graphql-client#118]
Hi
I'm trying to connect with my Keystone JS app.
I need to use a mutation to make a login and get the user's token.
**This is login.gql:**

type Mutation {
  authenticateUserWithPassword(email: String!, password: String!): UserAuthenticationWithPasswordResult!
}

type Query {
  authenticatedItem: AuthenticatedItem
}

union AuthenticatedItem = User

union UserAuthenticationWithPasswordResult = UserAuthenticationWithPasswordSuccess | UserAuthenticationWithPasswordFailure

type UserAuthenticationWithPasswordSuccess {
  sessionToken: String!
  item: User!
}

type UserAuthenticationWithPasswordFailure {
  message: String!
}

mutation {
  authenticateUserWithPassword(
    email: "user@example.com",
    password: "1234567890"
  ) {
   ... on UserAuthenticationWithPasswordSuccess {
    item {
      id
      name
      email
    }
  }
    ... on UserAuthenticationWithPasswordFailure {
      message
    }
  }
}

**I get those error when I run npm run dev:**
Unknown type "UserAuthenticationWithPasswordSuccess"
Unknown type "UserAuthenticationWithPasswordFailure"

Do I doing something wrong?
Thanks

**Comment by Diizzayy** [comment]
@yalondpsi A few points to take note of, the type definitions exist on the GraphQL API's schema  and hence shouldn't be manually added to your query / mutation definitions.

> I get those error when I run npm run dev:
Unknown type "UserAuthenticationWithPasswordSuccess"
Unknown type "UserAuthenticationWithPasswordFailure"

These errors indicates that your Keystone system hasn't been extended to support authentication, you need to use the `createAuth` function to do so, ie: [KeyStone JS Authentication Docs](https://keystonejs.com/docs/apis/auth)

Once you've utilized `createAuth`, your GraphQL schema will then have the type necessary for authentication, at which point your login query would be as seen below:

`login.gql`
```gql
mutation Login ($email: String!, $password: String!) {
  authenticateUserWithPassword(email: $email, password: $password) {
    ... on UserAuthenticationWithPasswordSuccess {
      item {
        id
        name
        email
      }
    }
    ... on UserAuthenticationWithPasswordFailure {
      message
    }
  }
}
``` 

- Usage

```vue
<script lang="ts" setup>
async function handleLogin() {
  const result = await GqlLogin({
    email: 'user@example.com',
    password: '1234567890'
  })

  console.log('handleLogin', result)
}
</script>
```

**Comment by yalondpsi** [comment]
@Diizzayy Hi
Thank you very much for the detailed answer.
I will try it

**Comment by yalondpsi** [comment]
Working :)
I also added the 'sessionToken' to return a token from the mutation function Login.
Maybe the next question is not in the scope of the support of this module, but can you please tell me or refer me:
Where and how I store the token - to use it with the next gql calls to the api?
Thank you !!

**Comment by Diizzayy** [comment]
> Where and how I store the token - to use it with the next gql calls to the api?

This module provides a [useGqlToken composable](https://nuxt-graphql-client.web.app/getting-started/composables#usegqltoken) which can be used to attach your Auth Token to subsequent GraphQL requests.

```vue
<script lang="ts" setup>
async function handleLogin () {
  const result = await GqlLogin({
    email: 'user@example.com',
    password: '1234567890'
  })

  if (!result) { return }

  // apply token to future requests
  useGqlToken(result.login.sessionToken)
}
</script>
```

> Where and how I store the token

You'll have to decide between storing your token in either a cookie ( **my recommendation** ) or in local storage based on your app's requirements (SSR etc), after doing so you can then create a nuxt plugin that will retrieve the token ( from cookie / local storage ) then apply it using `useGqlToken`.

- Below is an example retrieving a token stored using cookie and applying it in your app.

ps: Have a look at the KeyStoneJS documentation on [Authentication](https://keystonejs.com/docs/guides/auth-and-access-control) and [Sessions](https://keystonejs.com/docs/apis/session#session-stores)

`nuxt-app/plugins/init.ts`
```ts
export default defineNuxtPlugin(() => {
  const token = useCookie('<cookie_name>')

  if (token.value) { useGqlToken(token.value) }
})
```

**Comment by yalondpsi** [comment]
@Diizzayy Wow
Thank you again! much appriciated!!!

**Comment by yalondpsi** [comment]
Hi @Diizzayy 
I think there is a bug, not sure:
when I run yarn dev of the nuxt 3 app (latest rc 4) and the graphql api is down, I get an error:

**Cannot start nuxt:  Failed to load schema for "gql-sdk.ts"**                                                                                             
        Failed to load schema from http://localhost:3000/api/graphql:
        Unexpected token < in JSON at position 0
        SyntaxError: Unexpected token < in JSON at position 0

Thank you

**Comment by Diizzayy** [comment]
> when I npm run dev of the nuxt 3 app (latest rc 4) and the graphql api is down, I get an error:

@yalondpsi This module currently requires an active GraphQL api ( for Code Generation )

**Comment by yalondpsi** [comment]
@Diizzayy understood

**Comment by ourvisualbrain** [comment]
@Diizzayy -

> This module currently requires an active GraphQL api (for Code Generation)

are you saying that this will not work if your graphql api is being served by the nuxt app itself?

i too am seeing the error:

> Unexpected token < in JSON at position 0

is the solution to save my introspection to json, then reference that?

in my nuxt.config.ts, if i add the following:
```
  'graphql-client': {
    codegen: false
  },
```
then it will run, however, in my setup function
```
  async setup () {
    const { data } = (await useAsyncGql({
      operation: 'AllThings'
    }))
    const things = data._rawValue.allThings.nodes
    return {
      things
    }
  }
```

i have to use the _rawValue to get to my actual data - is this the effect of no codegen for me?
