### ISSUE TITLE
How to fix ExperimentalWarning

### ISSUE THREAD

**Issue by marcusarnfast** [Diizzayy/nuxt-graphql-client#140]
Is there a fix for the following?

ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time                                                                                                   09:07:50
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by Diizzayy** [comment]
This isn't an actual bug nor error for your app, but rather a warning that experimental NodeJS features are being used within your app or it's dependencies. I know the warnings are noisy but they can be safely ignored.
