### ISSUE TITLE
Variable paramater in query behavior 

### ISSUE THREAD

**Issue by jeremy-daude** [Diizzayy/nuxt-graphql-client#148]
Hello

I try my luck here if its possible issue with this gql client for nuxt3 (and thank you very much for this one !)

I'm trying to make GQL call inside a component with a variable ID as a paramater for my query., as follow :

`const { data: asset } = await useAsyncData('asset', async () => GqlGetAsset(
    { preview: false, id: props.entry.target.sys.id }
  ),
  {
      transform: asset => asset.asset
  }
);
`

It works, but only for the first iteration over 30 items, so i have 30x the same result, its like the query get stuck at the first call somehow.

I'm 100% sure than my prop is updated with different ID passed by the parent in a v-for.

Maybe my approach is bad but i need to make calls by id on this component.

Thanks a lot.

**Comment by Diizzayy** [comment]
@jeremy-daude the `useAsyncData` composable is likely the reason for this behavior, upon it's initial call the data is cached by the key (ie: asset) that you've passed, and reused for subsequent calls.

I'd suggest using a unique key per asset as seen below

```ts
const propId = props.entry.target.sys.id
const { data: asset } = await useAsyncData('asset-' + propId, () => GqlGetAsset({ preview: false, id: propId }));
```

The `useAsyncData` composable also takes a property called `initialCache` which allows you to forego caching, that can be utilized as seen below

```ts
useAsyncData('key', () => Example(), { initialCache: false })
```

**Comment by jeremy-daude** [comment]
@Diizzayy Thank you so much ! your explanation of useAsyncData is better than the whole courses i take for this functionality. 

Everything is working as expected now. 

Again thank you :)
