### ISSUE TITLE
Uncaught SyntaxError: The requested module '/node_modules/graphql-request/dist/index.js?v=1f86a9fa' does not provide an export named 'GraphQLClient' (at index.mjs:2:1)

### ISSUE THREAD

**Issue by procrates** [Diizzayy/nuxt-graphql-client#158]
Any idea what is causing this on the latest Nuxt 3 release RC7?

**Comment by Diizzayy** [comment]
@procrates Any additional information here would be useful, can you also post the output of `yarn nuxi info`

**Comment by procrates** [comment]
------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `modules`, `runtimeConfig`
- Runtime Modules:  `nuxt-graphql-client@0.1.14`, `@nuxtjs/tailwindcss@5.3.2`, `@formkit/nuxt@1.0.0-beta.11-0dd967c`
- Build Modules:    `-`
------------------------------

And btw. With a fresh install:
`Uncaught SyntaxError: The requested module '/.nuxt/gql-sdk.ts' does not provide an export named 'getSdk' (at index.mjs:4:1)`

**Comment by Diizzayy** [comment]
Closing for the moment, as this was resolved in an earlier release.
