### ISSUE TITLE
Stackblitz preview not working - graphql package missing

### ISSUE THREAD

**Issue by mickasmt** [Diizzayy/nuxt-graphql-client#16]
Hi,

I just tested the preview on Stackblitz and the graphql package is missing. I get the following error:

` ERROR  Cannot start nuxt:  Cannot find package 'graphql' imported from /home/projects/kkvizxqln.github/node_modules/@graphql-codegen/cli/index.mjs`

I was able to solve the problem with `npm i graphl` in the terminal but I hope you can fix this problem so that we don't have to do it manually.

Thanks for this new module. Keep going on !

**Comment by Diizzayy** [comment]
@mickasmt Thank you for pointing that error.

This problem appears to be specific to the Stackblitz environment. In your local development `nuxt-graphql-client` is the only package you need to install

**Comment by mickasmt** [comment]
Thank you for this return.
