### ISSUE TITLE
Defer running of mutation so it's not running on component setup

### ISSUE THREAD

**Issue by MrTeapot** [Diizzayy/nuxt-graphql-client#161]
I'm using ```useAsyncGql``` to run a mutation. I'm defining it in the component setup, but I want to defer running the mutation until a button is clicked.  When the button is clicked, I run the refresh() function.

However, the mutation is also running on component setup. I wish to prevent that because it's polluting the error ref and making an unneccesary request.

I tried using lazy: true in the configuration:

```
<script setup>
const { data, error, refresh, pending } = await useAsyncGql("createTodo", {
  todo: addTodo
}, {
  lazy: true
});

const submit = async () => {
  await refresh();
}
</script>
```
This code will attempt to run the mutation on component load.

How can I prevent it from running on component setup? :)

**Comment by Diizzayy** [comment]
@MrTeapot Apologies for the late reply.

> I'm defining it in the component setup, but I want to defer running the mutation until a button is clicked. When the button is clicked, I run the refresh() function

I understand your case here, though I don't think `useAsyncGql` is the right fit here. A better approach might be to call `GqlCreateTodo` in the submit function, If you need access to it's return data elsewhere you can define a script global variable to store it:

```vue
<script lang="ts" setup>
const data = ref(null)

const submit = async () => {
  await GqlCreateTodo({ todo: addTodo }).then(({ createTodo }) => {
    data.value = createTodo
  })
}
</script>
```

**Comment by MrTeapot** [comment]
Thanks for getting back to me. 
Oh nice, I didn't realize that functions are generated like that! Cool stuff.

I'll give it a try and then post my solution here. Hopefully I can contribute with adding this to the docs afterwards.

**Comment by TheDutchCoder** [comment]
This solution works, but I think it would be cleaner if there was a native alternative.
How about something like:
```vue
<script setup lang="ts">
const { data, error, refresh, pending } = await useAsyncGql("createTodo", {
  todo: addTodo
}, {
  lazy: true,
  defer: true, // would not execute the call until `refresh` was called
});
</script>
```

**Comment by MrTeapot** [comment]
> This way we wouldn't need to define custom refs to keep track of data and assign it.

I agree, that would be way cleaner!
Atm I'm using a composable function that accepts the GqlCreateTodo, or any Gql mutation/query, and returns refs and functions like pending, execute, errors, data, etc.

**Comment by Diizzayy** [comment]
@MrTeapot @TheDutchCoder The desired behavior here can be achieved by passing the `immediate: false` flag option, doing so would delay the request until either `refresh` or `execute` is manually called.

```ts
const { refresh, execute } = await useAsyncGql("createTodo", {
  todo: addTodo
}, {
  immediate: false
});

// OR
const { refresh, execute } = await useAsyncGql({
  operation: "createTodo",
  variables: { todo: addTodo  },
  options: {
    immediate: false
});
```
