### ISSUE TITLE
useAsyncGql types error with transform

### ISSUE THREAD

**Issue by melrefaie** [Diizzayy/nuxt-graphql-client#163]
when using useAsyncGql i got errors with types while using transform like this

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/25461028/186667528-24304e06-a5bf-4e7c-9859-24f0da90ae9f.png">
<img width="752" alt="image" src="https://user-images.githubusercontent.com/25461028/186667917-b19a660e-9a98-41cd-8816-00dee125ba10.png">

while using useAsyncData works fine 

<img width="671" alt="image" src="https://user-images.githubusercontent.com/25461028/186668018-af52f957-89bd-407a-9f42-af58bc34bb6f.png">

note: code works fine for both but a lot of types errors

**Comment by Diizzayy** [comment]
@melrefaie Thanks for raising this issue. The `useAsyncGql` function's current implementation doesn't pass through the types to the options property, which results in `transform` / `pick` being untyped ( I'll address this in a fix today)

As for the type issue with `slug`, I assume it's expecting a type of string whereas the properties returned by `route.params` are `string | string[]`

`data.users_by_id` should most likely be changed to the actual name of the query ie `data.getUser` for example

Also, Your use of `transform` has no effect here,

**Comment by jxlstudio** [comment]
@Diizzayy how would I go about fixing the error I get from the route.params type mismatch for slug?
