### ISSUE TITLE
How to run queries server-side in middleware?

### ISSUE THREAD

**Issue by TheDutchCoder** [Diizzayy/nuxt-graphql-client#173]
I can't for the life of me figure out how to run any of the queries in server middleware.

The composable can't be used, nor the generated queries (no Vue aliases allowed server-side), so I'm mightily confused as to how to get the server to run a query.

My use case is auth middleware that will fetch the user from GraphQL based on their httpOnly cookie.
This also happens on the client-side after a login of course, but I also need to do this on initial request on the server side to see if the user is authed.

Any help would be appreciated!

**Comment by Diizzayy** [comment]
@TheDutchCoder A current limitation of this module ( will be addressed in the very next release ) is the inability to execute in the nitro context ( server api / middlewares ).

However though, what you can do is extract that auth initialization logic to a server plugin where you have access to the `httpOnly` cookie and are indeed able to execute queries / mutations. This is also the recommended approach to share auth state across  server and  client

**Comment by TheDutchCoder** [comment]
@Diizzayy Thanks for the reply! I realize I should've posted this in "Discussions "instead, so I'll close the issue.
I'll take a look at the plugin approach, but I believe there you can't read out the headers, but maybe I'm wrong.

Thanks again!

**Comment by TheDutchCoder** [comment]
I'm 100% wrong, you do have access to headers, so this is perfect, thanks!

**Comment by Diizzayy** [comment]
@TheDutchCoder No problem at all, I’m glad to hear the solution works for you.

**Comment by BSBjorn** [comment]
Hello! Did the limitation get fixed? I can't get the module to work on a server middleware....? 
Only get the error: "useAsyncGql is not defined"

is there a way yo import the module?

**Comment by Diizzayy** [comment]
@BasCozijn I've outline an example for server side usage below:

`./queries/ships.gql`:
```gql
query ships($limit: Int = 5) {
  ships(limit: $limit) {
    id
    name
  }
}
```

you'll then be able to execute it as seen here (`./server/api/demo.get.ts`):
```ts
export default eventHandler(async () => {
  const data = await GqlShips()

  return data
})
```

however, note that there's currently an issue with the types returned on the server side
