### ISSUE TITLE
How to add headers?

### ISSUE THREAD

**Issue by b805rohit** [Diizzayy/nuxt-graphql-client#174]
runtimeConfig: { 
    public: {
      'graphql-client': {
        clients:{
          default:{
            host:"http://localhost:8080/v1/graphql",
            headers:{
              "content-type":"application/json",
              "x-hasura-admin-secret":"####"
            }
          }
        }
      },
    },
  }

Could not obtain introspection result, received: {"errors":[{"extensions":{"code":"access-denied","path":"$"},"message":"x-hasura-admin-secret/x-hasura-access-key required, but not found"}]}
  Error: Could not obtain introspection result, received: {"errors":[{"extensions":{"code":"access-denied","path":"$"},"message":"x-hasura-admin-secret/x-hasura-access-key required, but not found"}]}

**Comment by Diizzayy** [comment]
@b805rohit Your configuration looks alright, So I assume the issue here might be with your hasura API. I'd suggest ensuring that introspection is enabled
