### ISSUE TITLE
'Invalid host defined options' error on nuxt 2

### ISSUE THREAD

**Issue by thisismydesign** [Diizzayy/nuxt-graphql-client#178]
`nuxt@2.15.3` on node `14.20.0` getting the following error when I add `nuxt-graphql-client` to the nuxt config:

```
 FATAL  Invalid host defined options                                                                                                                                                       14:23:36

  at ModuleContainer.module.exports (node_modules/nuxt-graphql-client/dist/module.cjs:2:3)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:239:34)
  at node_modules/@nuxt/utils/dist/utils.js:639:43
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:55:5)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:478:5)
```

Background: This is a great gql client for nuxt 3. We would like to incrementally migrate from nuxt 2 to nuxt 3 and would like to change to this client in the process.

**Comment by Diizzayy** [comment]
@thisismydesign Thank you for reaching out, and for your interest in the module.

Unfortunately, `nuxt-graphql-client` doesn't current support Nuxt 2 nor bridge so that might make your current incremental migration a bit more complicated.

**Comment by thisismydesign** [comment]
@Diizzayy Thanks. Closing then
