### ISSUE TITLE
useGqlHeaders and useGqlToken aren't reactive

### ISSUE THREAD

**Issue by TheDutchCoder** [Diizzayy/nuxt-graphql-client#180]
When using `useGqlHeaders` or `useGqlToken`, I would assume that the passed values can be refs and that the headers/tokens would update on subsequent requests if the refs change.

A simple use-case is sending along JWT access-tokens that change after each GraphQL call.

Currently it will use just use the initial passed in value.

**Comment by Diizzayy** [comment]
> Currently it will use just use the initial passed in value.

Indeed.

Allowing reactive values to be passed and updated accordingly would certainly be a welcomed improvement, I had initially avoided that very implementation to reduce unintended side effects and ultimately make the debugging process easier on developers' ( having to explicitly call the functions when you wish to affect the underlying request )

**Comment by sweetroll** [comment]
Hey @Diizzayy I am having issue with the 'Currently it will use just use the initial passed in value' mentioned above. I have implemented a basic JWT refresh token middleware but when I attempt to clear out the headers via useGqlHeaders or useGqlToken the are sent anyway.

Accepting reactive values would be a great enhancement but could you allow static values to work if updated in a middleware?

**Comment by stlbucket** [comment]
I think this is a question related to this - I can't find out how to properly implement it though:

Before every request, I want to call:

```
useGqlHeaders(useRequestHeaders['cookie']));
```

or do the equivalent via config.  I'm not able to figure out how, though.  I see this is closed, and it sounds like what I'm trying to do, but I can't find any documentation on how to implement.
