### ISSUE TITLE
Using fragments from other gql files

### ISSUE THREAD

**Issue by TomDoFuture** [Diizzayy/nuxt-graphql-client#182]
in the queries folder I have different files containing queries for each page.

Sometimes they share the same fields which I want to put in a fragment,

too bad I can't "import" fragments from another file

I need to put all these queries + fragment in one file.

How do I fix this?

**Comment by TheDutchCoder** [comment]
You actually can use fragments, but it's a bit different form using JS files with `gql` and imports.

Example:
```js
// MyFragment.gql
fragment BaseAccountFields on Account {
  id
  username
}
```

```
// GetAccount.gql
query getAccount($id: ID!) {
  ...BaseAccountFields
}
```

This will work just fine.

**Comment by TomDoFuture** [comment]
Thank you!
