### ISSUE TITLE
Force query documentation

### ISSUE THREAD

**Issue by Pjort** [Diizzayy/nuxt-graphql-client#191]
I lack the documentation needed to fire the same query multiple times within a session and it actually making a request to the graphql endpoint each time, instead of only once and the using cached data.

**Comment by tasiotas** [comment]
same here. How can we clear cache or hit API again?

**Comment by Diizzayy** [comment]
@Pjort @tasiotas The cache is only hit when either `useAsyncGql` or `useAsyncData` is used, however though we only recommend using `useAsyncGql` when querying data that is needed to load a page. GqlFunctions should be used whenever possible ( their response is never cached )

### with `useAsyncGql`, you can disable initialCache 

```ts
const { data, error } = await useAsyncGql({
  operation: 'launches',
  variables: { limit: 8 },
  options: {
    initialCache: false
  }
})
```

**Comment by Pjort** [comment]
> @Pjort @tasiotas The cache is only hit when either `useAsyncGql` or `useAsyncData` is used, however though we only recommend using `useAsyncGql` when querying data that is needed to load a page. GqlFunctions should be used whenever possible ( their response is never cached )
> 
> ### with `useAsyncGql`, you can disable initialCache
> ```ts
> const { data, error } = await useAsyncGql({
>   operation: 'launches',
>   variables: { limit: 8 },
>   options: {
>     initialCache: false
>   }
> })
> ```

Thanks for this answer, very usefull.

When you say GqlFunctions which ones are you refering to? Do you mean just using the graphql-request lib with the gencode?

**Comment by Diizzayy** [comment]
@Pjort This modules automatically generates what we refer to as `GqlFunctions` based on the queries / mutations that you have defined.

So for instance, Given the query below:

```gql
query MyShips {
  ships {
    id
  }
}
```

a GqlFunction called `GqlMyShips` would be auto-generated and usable throughout your app, the syntax woud be

```ts
const handleDemo = async () => {
  const result = await GqlMyShips()
  // do something with `result.ships`
}
```

**Comment by Pjort** [comment]
Oh that sounds so good! I will test it out for sure!

But the documentation doesn't mention this I think? When I have played around with it a bit I intend to make a pull request on the documentation for these things. I can't be the only one that didn't know this and needed this for a project 😊

**Comment by Pjort** [comment]
Didn't mean to close it untill I have added the documentation

**Comment by Diizzayy** [comment]
The documentation certainly needs an overhaul! I intend to begin improving it in the near future, You can welcome to assist with the pull requests if you like, I'd appreciate it

**Comment by Diizzayy** [comment]
Documentation has been updated to reflect [`Gql Functions`](http://localhost:3000/getting-started/gql-functions).
