### ISSUE TITLE
Move queries to SFC

### ISSUE THREAD

**Issue by iBobik** [Diizzayy/nuxt-graphql-client#192]
[Single file components are best practice.](https://vuejs.org/guide/scaling-up/sfc.html#why-sfc)

Could it be used also for GraphQL? Similarly like here:
- https://github.com/wheatjs/vite-plugin-vue-gql
- https://apollo.vuejs.org/guide/apollo/

**Comment by Diizzayy** [comment]
@iBobik The decision to forego allowing writing GraphQL documents (queries / mutation) within the SFC is at the heart of this module, and is also one that I don't see us changing anytime soon.

**Comment by iBobik** [comment]
Aha, so it is strategic decision. Could you, please, explain it, so I can learn why I should not do it?Honza Pobořil💬Signal17. 9. 2022 v 12:20, Conrawl Rogers ***@***.***>:﻿
@iBobik The decision to forego allowing writing GraphQL documents (queries / mutation) within the SFC is at the heart of this module, and is also one that I don't see us changing anytime soon.
