### ISSUE TITLE
useGqlToken/useHeaders with SSR

### ISSUE THREAD

**Issue by nikitin-dev** [Diizzayy/nuxt-graphql-client#216]
Hi there!
I have a problem with reassigning request headers.
I'll start by describing my situation. I am using Nuxt version 3.0.0-rс.9 and strapi for the backend.
In cookies, I have a JWT token, which is written after user authorization. Strapi provides the ability to request user data by forwarding a header with a JWT token.
I want to receive information about the user's authentication status on the server side and, depending on the response, render the necessary markup on the server as well.

Here is my script in app.vue

```
<script lang="ts" setup>
import { useAuthStore } from "~~/store/auth";

const authStore = useAuthStore();
const jwt = useCookie("jwt");

const userAuth = () => {
  if (jwt.value) {
    useGqlToken(jwt.value);
    return GqlUser();
  }
};

const { data: user } = await useAsyncData("user", userAuth);

if (user.value?.me) {
  authStore.authUser({
    jwt: jwt.value,
    user: user.value.me
  });
}
</script>
```

As you see, i'am trying to reassign header using "useGqlToken" each time.
The problem is:
When i authorize the user №1, i get JWT, reload page and it works. My user is authorized and markup was rendered on the server.
But when i logout and authorize user №2, i also get ANOTHER JWT token, reload page and i get data of user №1.

This is strange behavior, because in fact request must be executed with a new one JWT token. I dived into source code and console logged some stuff:

Action 1:

1. User №1 authorization
2. Reloading page

![image](https://user-images.githubusercontent.com/110449514/194155177-205b88de-33d6-46b9-b464-6c10914e5e6a.png)

As you can see, we get valid jwt token in the useGqlToken function and valid request header in the setGqlState function as well
In this case, i get expected result i.e. data of user №1.

Action 2:

1. User №1 logout (jwt removed from cookies)
2. User №2 authorization
3. Reload page

![image](https://user-images.githubusercontent.com/110449514/194157125-821bc7cc-8304-4769-904a-377ec9d07649.png)

We also get valid jwt token in the useGqlToken function and valid request header in the setGqlState function as well
But in this case i get data of user №1 AGAIN.

The first log, named "TOKEN" it is:
![image](https://user-images.githubusercontent.com/110449514/194155517-d289837f-b901-4f14-a9dc-da7e7f0f6213.png)

The second log, named INSTANCE it is result of "setGqlState" function execution:
![image](https://user-images.githubusercontent.com/110449514/194155660-1c437ec9-e082-4f82-bc73-008a96e6a866.png)

It looks like it's not working for reassigning token in headers. Or am I just doing something wrong?

Thanks in advance, looking forward to your reply)

**Comment by Diizzayy** [comment]
@nikitin-dev I've been unable to replicate this behavior locally. 

- Token is initially set in server plugin by extracting JWT from cookie, then calling `useGqlToken('<jwt>')`
- Token is stripped by calling `useGqlToken(null)` to logout the user
- Token is then updated again by recalling `useGqlToken('<newToken>')`

Any additional details you may be able to provide, or perhaps a reproduction would be a great help in addressing this

**Comment by nikitin-dev** [comment]
That solved my issue.
@Diizzayy, thanks a lot! You're really awesome guy. Thanks for your productive work and quick replies!

**Comment by Diizzayy** [comment]
@nikitin-dev Happy to help!
