### ISSUE TITLE
Make queries by GET method 

### ISSUE THREAD

**Issue by mercs600** [Diizzayy/nuxt-graphql-client#219]
We are wondering can we use GET to make queries ? Some of them we would like to cache and with POST we are not able to do this on server side. 

I noticed this library use https://github.com/prisma-labs/graphql-request as the client and there is possibility to create client with GET method.  
On the other hand I noticed you are working on https://github.com/Diizzayy/ohmygql which is used as client in the edge version. Why won't you use graphql-request lib ? 

So my question is: are you planning to give possibility to make some queries as GET method ?

**Comment by franzwilding** [comment]
+1 for caching specific queries via GET urls
