### ISSUE TITLE
Change dynamically client endpoint

### ISSUE THREAD

**Issue by aspitrine** [Diizzayy/nuxt-graphql-client#232]
Hi,
It's not a bug but a feature. 

I think it's a really specific case but i need to set the endpoint computed from my current url and it's not possible at runtime.

Can you add a composable like `useGqlToken` to change the endpoint of my client ?

You are using graphql-request with `new GraphQLClient` and they have a method `client.setEndpoint(newEndpoint)` to do this.

Thank you for your work

**Comment by aspitrine** [comment]
I'm not really good with type but i think it's look like this

```ts
// src/runtime/composables/index.ts
export const useGqlEndpoint = (endpoint: String, client: GqlClients = 'default') => {
    const { instance } = state.value?.[client]
    instance.setEndpoint(endpoint);
}
```

**Comment by Diizzayy** [comment]
@aspitrine As per your request, A PR adding this functionality is on the way.

**Comment by Diizzayy** [comment]
@aspitrine This functionality has been added in `v0.2.1` via the [`useGqlHost` composable](https://nuxt-graphql-client.web.app/getting-started/composables#usegqlhost)

**Comment by aspitrine** [comment]
Thanks a lot ! 

Have a nice day 😄
