### ISSUE TITLE
credentials:include wont work as expected

### ISSUE THREAD

**Issue by cur1ou5soul** [Diizzayy/nuxt-graphql-client#233]
In our projects, we have multiple clients talking to Apollo as a middleware. We need to send our cookies to apollo-server so that the Session Relevant data can be fetched via apollo. 

If I set credentials:include and also all CORS headers on server-side no Cookies are sent to our server from the browser.

Hopefully someone can help me with this. 

regards,

**Comment by Diizzayy** [comment]
@cur1ou5soul You should be able to call `useGqlCors` in a plugin to configure how credentials are handled across all clients

`/nuxt-app/plugins/cors.ts`
```ts
export default defineNuxtPlugin(nuxtApp => {
  useGqlCors({ credentials: 'include' })
})
```

**Comment by cur1ou5soul** [comment]
Just tried actually this doesent work. How can I prove that the setting is enabled?

**Comment by Diizzayy** [comment]
> Just tried actually this doesent work

I've just tested it locally against our API and the requests do in-fact respect the credentials options.

One thing to note is that `useGqlCors` accepts an optional `client` param to indicate which client to interface with, when omitted it falls back to the default client.

> How can I prove that the setting is enabled?

quick 'dirty' way to check the gql client state is:

```ts
export default defineNuxtPlugin((nuxtApp) => {
  useGqlCors({ 
    credentials: 'include',
    // client: '<client-name>' // defaults to: 'default'
  })

  const defaultClient = nuxtApp?._gqlState.value?.default ? 'default' : Object.keys(nuxtApp?._gqlState.value)[0]

  if (defaultClient) {
    console.log('Client Credentials:', nuxtApp?._gqlState?.value?.[defaultClient]?.options?.credentials)
    // should output: "Client Credentials: include"
  }
})
```

**Comment by cur1ou5soul** [comment]
First of all you are awesome 🙏  

Well it says it's on Include but in my local environment where I have to use unsigned certificates my cookies aren't passed through. Can this be a reason for cookies not being sent?

**Comment by Diizzayy** [comment]
@cur1ou5soul Closing for now as per our conversation on discord. Feel free to reach out to me for any additional assistance.
