### ISSUE TITLE
Subscription and missing generated types.

### ISSUE THREAD

**Issue by jojco** [Diizzayy/nuxt-graphql-client#234]
First question -  It's possible to use Graphql Subscriptions?

Second - I cannot generate types from our graphql api server. After 'yarn dev' I don't get any error or warning (looks like generator recived schema), but in .nuxt/... I don't find any gerated files. (on api  https://api.spacex.land/graphql/ everything works fine)

Could be a problem with our schema which included graphql subscription ? 
Thanks.

**Comment by Diizzayy** [comment]
> It's possible to use Graphql Subscriptions?

Not currently, though it's planned for a near release.

> I cannot generate types from our graphql api server. After 'yarn dev' I don't get any error or warning (looks like generator recived schema), but in .nuxt/... I don't find any gerated files. (on api https://api.spacex.land/graphql/ everything works fine)

This is strange given that there are no errors, a `gql` directory should be generated within `.nuxt`.

Would you be able to provide a minimal reproduce or grant me access to your api for me to have a closer look?

**Comment by Diizzayy** [comment]
Closing for now, will reopen if needed.
