### ISSUE TITLE
Missing build import files

### ISSUE THREAD

**Issue by daniluk4000** [Diizzayy/nuxt-graphql-client#236]
In DEV env, all types I need are located in #build/gql/default: 
![изображение](https://user-images.githubusercontent.com/10450717/197338891-9949bed3-674d-47ca-8b82-7d571b0d1585.png)

But on build this file is not present here: 
![изображение](https://user-images.githubusercontent.com/10450717/197338909-bb2b8d77-0164-4d92-8b3a-164d8e007223.png)

Which leads to error like  'Role' is not exported by virtual:nuxt:/WebstormProjects/ProjectName/.nuxt/gql/default.mjs, imported by src/store/index.ts

The config I use is a default one

**Comment by Diizzayy** [comment]
@daniluk4000 Thank you for raising this issue, recent releases introduced a few performance enhancements, one which disables code generation during the build phase. `v0.2.6` is on the way and fixes this by putting this behavior being a flag that can be manually enabled.

**Comment by daniluk4000** [comment]
@Diizzayy thank you!

**Comment by Diizzayy** [comment]
@daniluk4000 `v0.2.6` was just released.

**Comment by daniluk4000** [comment]
That was so fast. All working fine now. Thank you again.
