### ISSUE TITLE
Cookies not being sent to server

### ISSUE THREAD

**Issue by ShreyAmbesh** [Diizzayy/nuxt-graphql-client#246]
I am facing an issue where the cookies are not being sent from browser to server. It only happens when call is made from the browser for example if there is a graphql call in the setup function then all the cookies are sent. As it's setup function so t's rendered from the server due to the SSR but if I make the same graphql call on a button click then the cookies are not being sent. 
I have already set the plugin for credentials to be included in useGqlCors

**Comment by Diizzayy** [comment]
The issue here is likely with the browser or perhaps even the server's configuration, I'd need a bit more information to better understand what you're facing here and help you in resolving it.

Would you be able to reach out to me on discord ( @ Diizzayy#1964 ) so I can have a closer look?

**Comment by Diizzayy** [comment]
@ShreyAmbesh Closing as per our conversation on discord.

**Comment by Dermatit** [comment]
@Diizzayy Hi, I have exactly the same issue. What was the solution for this issue due to your discord conversation?
