### ISSUE TITLE
Import fails with Nuxt 3 RC.14

### ISSUE THREAD

**Issue by boboldehampsink** [Diizzayy/nuxt-graphql-client#250]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0-rc.14`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `srcDir`, `vite`, `alias`, `build`, `modules`, `i18n`, `tailwindcss`, `graphql-client`, `runtimeConfig`, `app`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.3-27790843.ad45be6`, `@nuxtjs/tailwindcss@6.1.3`, `nuxt-graphql-client@0.2.10`, `@/modules/routes`
- Build Modules:    `-`

### Describe the bug

```
 ERROR  [unimport] failed to find "useGqlHeaders" imported from "#imports"                                                                     10:11:59


 ERROR  [unimport] failed to find "useAsyncGql" imported from "#imports"                                                                       10:12:05


 ERROR  [unimport] failed to find "useGql" imported from "#imports"                                                                            10:12:07
```

### Expected behaviour

No import failures

**Comment by Diizzayy** [comment]
@boboldehampsink This should be resolved by running `npx nuxi clean`, deleting your lockfile (`yarn.lock` or `package-lock.json`) then re-installing the dependencies.

**Comment by gkkirilov** [comment]
Hey @Diizzayy, thanks for the fast update, but getting another error now 
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/8720012/202290800-02503fdb-c4a7-4e7e-8f18-dfae0f3fffee.png">

**Comment by Diizzayy** [comment]
@gkkirilov the The nullish coalescing assignment operator (`??=`) was introduced in `node v15`, it's being used in this module, hence the error if you're using an older version of node.

**Comment by boboldehampsink** [comment]
Updated package and to nuxt stable and now issue is gone
