### ISSUE TITLE
Cannot find name 'useAsyncGql'.ts in stable release

### ISSUE THREAD

**Issue by pzpsofficial** [Diizzayy/nuxt-graphql-client#253]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.3`
- Nuxt Version:     `3.0.0-rc.14`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.1.1`
- Builder:          `vite`
- User Config:      `vite`, `modules`, `runtimeConfig`, `build`, `app`
- Runtime Modules:  `nuxt-graphql-client@0.2.10`
- Build Modules:    `-`
------------------------------

### Describe the bug

I have just upgraded nuxt to latest stable release, and I get the following error:

`Cannot find name 'useAsyncGql'.`

Is it a known issue or something? 

### Expected behaviour

Being able to use `useAsyncGql` in vue files.

**Comment by Diizzayy** [comment]
@pzpsofficial try running `npx nuxi clean` and deleting your lockfile (package-lock.json) then re-installing the dependencies.

**Comment by pzpsofficial** [comment]
@Diizzayy Thanks! It worked like a charm, but now I am getting another error: `Unexpected token '??='` - but I guess that it's something related to Nuxt itself, what do you think?

**Comment by Diizzayy** [comment]
@pzpsofficial the `??` operator is used across nuxt and was introduced in `node v15^`, you'll have to update from version `v14.18.3`

**Comment by pzpsofficial** [comment]
@Diizzayy Oooh, so that's what makes a great developer great :D Thank you so much, it's working like a charm. Thanks again, and all best!

**Comment by Diizzayy** [comment]
@pzpsofficial Happy to help!
