### ISSUE TITLE
Duplicate identifier when using DatoCMS

### ISSUE THREAD

**Issue by FWORDIE** [Diizzayy/nuxt-graphql-client#26]
When using this with DatoCMS I get this error: 

> ERROR  16:09:12 [vite] Internal server error: Transform failed with 8 errors:                                                                                                                                                                                       16:09:12
> /Users/wordie/Documents/00 Projects/000 Portfolio/nuxt3-app/.nuxt/gql-sdk.ts:1550:2: ERROR: The symbol "CreatedAtAsc" has already been declared
> /Users/wordie/Documents/00 Projects/000 Portfolio/nuxt3-app/.nuxt/gql-sdk.ts:1551:2: ERROR: The symbol "CreatedAtDesc" has already been declared
> /Users/wordie/Documents/00 Projects/000 Portfolio/nuxt3-app/.nuxt/gql-sdk.ts:1560:2: ERROR: The symbol "UpdatedAtAsc" has already been declared
> /Users/wordie/Documents/00 Projects/000 Portfolio/nuxt3-app/.nuxt/gql-sdk.ts:1561:2: ERROR: The symbol "UpdatedAtDesc" has already been declared
> /Users/wordie/Documents/00 Projects/000 Portfolio/nuxt3-app/.nuxt/gql-sdk.ts:2072:2: ERROR: The symbol "CreatedAtAsc" has already been declared
> ...
>   Plugin: vite:esbuild
>   File: /Users/wordie/Documents/00 Projects/000 Portfolio/nuxt3-app/.nuxt/gql-sdk.ts
>   
>   The symbol "CreatedAtAsc" has already been declared
>   1548|    UpdatedAtAsc = '_updatedAt_ASC',
>   1549|    UpdatedAtDesc = '_updatedAt_DESC',
>   1550|    CreatedAtAsc = 'createdAt_ASC',
>      |    ^
>   1551|    CreatedAtDesc = 'createdAt_DESC',
>   1552|    DateAsc = 'date_ASC',
>   
>   The symbol "CreatedAtDesc" has already been declared
>   1549|    UpdatedAtDesc = '_updatedAt_DESC',
>   1550|    CreatedAtAsc = 'createdAt_ASC',
>   1551|    CreatedAtDesc = 'createdAt_DESC',
>      |    ^
>   1552|    DateAsc = 'date_ASC',
>   1553|    DateDesc = 'date_DESC',
>   
>   The symbol "UpdatedAtAsc" has already been declared
>   1558|    TitleAsc = 'title_ASC',
>   1559|    TitleDesc = 'title_DESC',
>   1560|    UpdatedAtAsc = 'updatedAt_ASC',
>      |    ^
>   1561|    UpdatedAtDesc = 'updatedAt_DESC'
>   1562|  }
>   
>   The symbol "UpdatedAtDesc" has already been declared
>   1559|    TitleDesc = 'title_DESC',
>   1560|    UpdatedAtAsc = 'updatedAt_ASC',
>   1561|    UpdatedAtDesc = 'updatedAt_DESC'
>      |    ^
>   1562|  }
>   1563|  
>   
>   The symbol "CreatedAtAsc" has already been declared
>   2070|    AutoplayKeyVidAsc = 'autoplayKeyVid_ASC',
>   2071|    AutoplayKeyVidDesc = 'autoplayKeyVid_DESC',
>   2072|    CreatedAtAsc = 'createdAt_ASC',
>      |    ^
>   2073|    CreatedAtDesc = 'createdAt_DESC',
>   2074|    DateAsc = 'date_ASC',
>   
>   The symbol "CreatedAtDesc" has already been declared
>   2071|    AutoplayKeyVidDesc = 'autoplayKeyVid_DESC',
>   2072|    CreatedAtAsc = 'createdAt_ASC',
>   2073|    CreatedAtDesc = 'createdAt_DESC',
>      |    ^
>   2074|    DateAsc = 'date_ASC',
>   2075|    DateDesc = 'date_DESC',
>   
>   The symbol "UpdatedAtAsc" has already been declared
>   2088|    TypeofworkAsc = 'typeofwork_ASC',
>   2089|    TypeofworkDesc = 'typeofwork_DESC',
>   2090|    UpdatedAtAsc = 'updatedAt_ASC',
>      |    ^
>   2091|    UpdatedAtDesc = 'updatedAt_DESC'
>   2092|  }
>   
>   The symbol "UpdatedAtDesc" has already been declared
>   2089|    TypeofworkDesc = 'typeofwork_DESC',
>   2090|    UpdatedAtAsc = 'updatedAt_ASC',
>   2091|    UpdatedAtDesc = 'updatedAt_DESC'
>      |    ^
>   2092|  }
>   2093|  `

  
  I assume it is related to [this issue](https://github.com/dotansimha/graphql-code-generator/issues/6925)
  
  Is it possible to fix this? Happy to provide more details

**Comment by FWORDIE** [comment]
Lil update:

Managed to fix the issue locally by editing the module.mjs with

`async function generate(options) {
  const schema = Object.values(options.clients).map((v) => !v?.token ? v.host : { [v.host]: { headers: { [v?.token?.name || "Authorization"]: `Bearer ${v.token.value}` } } });
  const [{ content }] = await generate$1({
    schema,
    silent: options.silent,
    documents: options.documents,
    generates: {
      [options.file]: {
        plugins: options.plugins,
        config: {
          skipTypename: true,
          useTypeImports: true,
          gqlImport: "graphql-request#gql",
          onlyOperationTypes: options.onlyOperationTypes,
          namingConvention: {
            enumValues: 'change-case-all#upperCaseFirst'

          }
        }
      }
    }
  }, false);
  return content;
}
`

**Comment by Diizzayy** [comment]
@FWORDIE Thank you for raising this issue, and finding the cause.

> I assume it is related to https://github.com/dotansimha/graphql-code-generator/issues/6925

I agree, and your fix changing the `namingConvention` for enums should be suffice to prevent others from running into this issue.

I'll push an update to have this addressed.
