### ISSUE TITLE
can not use cookies in query

### ISSUE THREAD

**Issue by iam-robi** [Diizzayy/nuxt-graphql-client#261]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.6.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `vite`, `dev`, `modules`, `inkline`, `runtimeConfig`, `typescript`, `build`, `css`, `graphql-client`
- Runtime Modules:  `@inkline/nuxt@3.1.4`, `@vueuse/nuxt@9.5.0`, `nuxt-graphql-client@0.2.13`, `@pinia/nuxt@0.4.4`
- Build Modules:    `-`

### Describe the bug

I tried to configure the module to take cookies and send them in the request but it does not work even when stating explicitly `proxyCookies: true` in the config. 

```js
 runtimeConfig: {
    public: {
      'graphql-client':{
        clients: {
          custom: {
            host: 'http://localhost:3008/graphql',
            proxyCookies: true
          }
        }
      },
```
     

### Expected behaviour

I had to use traditional  fetch to get the cookies sent with a graphql query : 
     

```js
       const query = query userProfile {
            userProfile{
                  data {
                   id
                   email
                   lastName
                   firstName
                   age
                   gender
                   createdAt
                   updatedAt
          }
     }
  }

  
  const querydata = {
    "operationName": "userProfile",
    "query": query
  }
  const { data, pending, error, refresh } = await useFetch('http://localhost:3008/graphql', { method: "POST", body: querydata, credentials: "include"});

  ```

**Comment by Diizzayy** [comment]
@iam-robi The `proxyCookies` flag is used to extract cookies from the client to be passed along to the GraphQL API during SSR.

As it pertains to client side requests, I suspect that what's preventing the cookies from being sent is the cors rules.

Try calling `useGqlCors({ credentials: 'include' })` before making the gql request

**Comment by iam-robi** [comment]
Thanks a lot , this solved the issue  !!

**Comment by Diizzayy** [comment]
@iam-robi Happy to help!

Also I suggest calling `useGqlCors` in a plugin to have it applied across the entire app.

`/nuxt-app/plugins/cors.client.ts`
```ts
export default defineNuxtPlugin(() => {
  useGqlCors({ credentials: 'include' })
})
```
