### ISSUE TITLE
When `extending` a theme with module it doesn't work.

### ISSUE THREAD

**Issue by cpreston321** [Diizzayy/nuxt-graphql-client#264]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`, `runtimeConfig`
- Runtime Modules:  `nuxt-graphql-client@0.2.11`
- Build Modules:    `-`

### Describe the bug

When you extend the theme the default graphql types do write over to the theme. In this example I called it playground and tried extending the main project. 

### Playground Types for GQL
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/6619884/205455250-7ba51ba0-4103-427b-bc21-8ae4bb14d8e5.png">

### Main Types for Theme Layer

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/6619884/205455506-2fa80df3-b90d-42ab-98fa-dd6a2bf0c8f3.png">

### Expected behaviour

Should work as intended with the same types carried over.

### Reproduction

https://stackblitz.com/edit/nuxt-graphql-c2hshq?file=.playground/nuxt.config.ts

### Additional context

This is a main feature of nuxt called `extends`. I'm not for sure if this a module issue more than, it's not preparing the correct types correctly using `nuxt prepare .playground`. Maybe a nuxt resolve issue ?

#### Goal

I want to create a theme layer that uses this module but when I go to test all the types that it resolves too but is not the using the correct ones so it doesn't work as intended.

**Comment by cpreston321** [comment]
More Details about `Layers` Here: 

### Getting Started 

https://framework-b2ht4snfw-nuxt-js.vercel.app/docs/getting-started/layers

### Layer Author Guide 

https://framework-b2ht4snfw-nuxt-js.vercel.app/docs/guide/going-further/layers#tips-for-authoring-layers

**Comment by Diizzayy** [comment]
@cpreston321 Your change has been released in `v0.2.20`
