### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'setHeader')

### ISSUE THREAD

**Issue by ririen** [Diizzayy/nuxt-graphql-client#30]
There is a problem with the latest Nuxt: `3.0.0-27490192.4253d2e`

`[nitro] [dev] [unhandledRejection] TypeError: Cannot read properties of undefined (reading 'setHeader')`

Line in code: https://github.com/Diizzayy/nuxt-graphql-client/blob/e45ed72dc2f826399d6e3a1b2779b4ca00ac0056/src/runtime/composables.ts#L260

**Comment by Diizzayy** [comment]
@ririen Thank you for raising this issue, a fix is on the way!
