### ISSUE TITLE
Newest version v0.2.25 on npmjs.com is missing on GitHub. Malicious release?

### ISSUE THREAD

**Issue by mamk95** [Diizzayy/nuxt-graphql-client#301]
The newest version of nuxt-graphql-client (0.2.25) was published to NPM on 2023-01-25, and currently is the most downloaded version of nuxt-graphql-client. See https://www.npmjs.com/package/nuxt-graphql-client?activeTab=versions

I cannot find the source code for version 0.2.25, only 0.2.24. Is the release malicious?

The last activity in the main branch was 2022-12-24 for the release of v0.2.24. See https://github.com/Diizzayy/nuxt-graphql-client/branches/all

The latest release and tags on GitHub are v0.2.24. See https://github.com/Diizzayy/nuxt-graphql-client/releases and https://github.com/Diizzayy/nuxt-graphql-client/tags

Screenshots:
![image](https://user-images.githubusercontent.com/10944333/215766211-31cf4802-4e3e-4be7-8d2b-3e81ba8dc9df.png)
![image](https://user-images.githubusercontent.com/10944333/215766291-9ff80d56-8f82-4d93-824d-cdedf9f61431.png)

**Comment by stuible** [comment]
There appears to be only one change in the compiled code from 0.2.24 to 0.2.25:

**from**
```
      if (!conf?.host) {
        throw new Error(`GraphQL client (${k}) is missing it's host.`);
      }
```
**to**
```
      if (!conf?.host) {
        logger.warn(`GraphQL client (${k}) is missing it's host.`);
        return;
      }
```

Found using Kaleidoscope
<img src="https://i.imgur.com/JRcVjRL.png" />

I can't explain  why this release isn't tagged or found on GitHub but it does not appear to me to be malicious.

**Comment by Diizzayy** [comment]
@mamk95 @stuible This release was not malicious, though It failed to appear on github due to a lapse cycle on my development machine at the time
