### ISSUE TITLE
Support graphql subscription

### ISSUE THREAD

**Issue by radudiaconu0** [Diizzayy/nuxt-graphql-client#32]
Can u make this library support graphql subscriptions? 
https://www.apollographql.com/docs/react/data/subscriptions/

**Comment by Diizzayy** [comment]
@radudiaconu0  I'm currently exploring options to enable support for GraphQL subscriptions whilst keeping the module as lightweight as possible.

Currently, we're using [GraphQL Request](https://github.com/prisma-labs/graphql-request) under the hood and unfortunately it does not support subscriptions.

**Comment by ThomasKoscheck** [comment]
are there any update or plans for this feature yet?

**Comment by Keyruu** [comment]
GraphQL Request now supports Subscriptions.

**Comment by likt0r** [comment]
Hi, are there any plans to integrate subscriptions now ?
