### ISSUE TITLE
Nuxt 3.4/3.5 runtime config changes might break module

### ISSUE THREAD

**Issue by just-maik** [Diizzayy/nuxt-graphql-client#324]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.19.1
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      devtools, modules, components, sitemap, security, nitro, typescript, css, postcss, runtimeConfig, rootDir, app
- Runtime Modules:  ####, nuxt-graphql-client@0.2.27, ####
- Build Modules:    -
------------------------------

### Describe the bug

When casually using nuxt-graphql-client with Nuxt 3.4.1 it will error the following:

[nuxt] [runtimeConfig] You are trying to access a public runtime config value (`graphql-client`) directly from the top level. This currently works (for backward compatibility with Nuxt 2) but this compatibility layer will be removed in v3.5. Instead, you can update `config['graphql-client']` to `config.public['graphql-client']`.

This is a deprecation in 3.4 that will be removed in 3.5 ([RC](https://github.com/nuxt/nuxt/pull/20082))

### Expected behaviour

As of Nuxt 3.5 it will be expected to access config.public

### Reproduction

https://stackblitz.com/edit/github-nzhhxz?file=app.vue

### Additional context

Still works fine in Nuxt 3.4

**Comment by just-maik** [comment]
Sorry for all the renaming. I'm just not used to coming up with good Issue names...

**Comment by Diizzayy** [comment]
closing as this warning is no longer displayed and wasn't a particular issue for this module.
