### ISSUE TITLE
Dynamic query variables

### ISSUE THREAD

**Issue by r-kocjan** [Diizzayy/nuxt-graphql-client#334]
Hey, I'm trying to dynamically add query variables like this 

```
const { data, refresh } = await useAsyncGql({
  operation: "institutions",
  variables: {
    ...(selectedCategories.value.length > 0 && {
      categories: selectedCategories,
    }),
    limit: 50,
    siteId: siteId,
  },
});
```

It works on first run, but doesn't work when categories are updated. I would like it to refresh when 'selectedCategories' are filled, I don't want to add this variable when there are no selected categories. Is this possible?

I tried to use refresh funciton, but it doesn't seem to work.

**Comment by IgorBoikoLiven** [comment]
@r-kocjan Hi there. Why did you close this issue? Did you find the solution?

**Comment by r-kocjan** [comment]
@IgorBoikoLiven Hey, in my case I was also able to pass an empty array, so my solution was to just always pass the ref like:
```categories: selectedCategories```. I think I didn't find a solution that would allow me to conditionally pass this variable.
