### ISSUE TITLE
Disable code generation on build phase

### ISSUE THREAD

**Issue by DenisNikonov** [Diizzayy/nuxt-graphql-client#36]
How can I disable code generation from the api schema on build stage?
The production backend does not allow me to parse the schema

**Comment by DenisNikonov** [comment]
At the moment, add an optional parameter that takes the path to the graphql schema, if the parameter is specified, the schema update does not happen.
As a solution option

**Comment by Diizzayy** [comment]
@DenisNikonov Thank you for your patience, I was away over the past couple days.

Your suggestion is certainly a valid workaround ( thanks for putting it forward ).

I'll update the module to allow schemas to be provided alongside the host to forego querying the host for code generation.

**Comment by DenisNikonov** [comment]
@Diizzayy Thank you for your reply!
If necessary, I can do PR.

**Comment by Diizzayy** [comment]
@DenisNikonov The PR is almost ready to go, you can have a look at #42 . Currently running a final test before merging.

**Comment by DenisNikonov** [comment]
Great! Thank you for your work!

**Comment by mathix420** [comment]
It may be great to add this to the documentation as well.
