### ISSUE TITLE
useAsyncGql is not defined

### ISSUE THREAD

**Issue by chebyrashka** [Diizzayy/nuxt-graphql-client#408]
### Environment

- Operating System: Darwin
- Node Version:     v18.16.1
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.1
- Package Manager:  npm@9.5.1
- Builder:          -
- User Config:      modules, imports, devtools
- Runtime Modules:  nuxt-graphql-client@0.2.31, @pinia/nuxt@0.5.1
- Build Modules:    -

### Describe the bug

I run into this issue 'useAsyncGql is not defined' when deploying to Netlify but running in local dev or building locally works fine. 

### Expected behaviour

On Netlify I'd expect it to run like in local dev

**Comment by chebyrashka** [comment]
IBK issue

**Comment by sinasita** [comment]
What do you mean by IBK issue? And what was your problem, i got the same error? Thank you!

**Comment by mirukuz** [comment]
also facing the same issue

**Comment by LePtiDev** [comment]
Same for me any solution ?

**Comment by Diizzayy** [comment]
@LePtiDev I'll have a look into this now, would you be able to provide a minimal reproduction?

**Comment by LePtiDev** [comment]
If you need a full project tell me i can try to reproduce from scratch

**Comment by LePtiDev** [comment]
no news ?
