### ISSUE TITLE
Allow type safe usage of useGqlError

### ISSUE THREAD

**Issue by some-user123** [Diizzayy/nuxt-graphql-client#468]
### Your use case

When defining a custom error handler using `useGqlError` I'd like to write a type safe function, e.g.:

Instead of:
```ts
useGqlError((err) => {
    console.error(err)
 })
```

I want to write:
```ts
useGqlError((err: GqlError) => {
    // Access err in a type safe way...
 })
```

### The solution you'd like

I'd like to import the type `GqlError`. Could not find a working export. (Ideally, this would be reflected in the [docs](https://nuxt-graphql-client.web.app/getting-started/composables#usegqlerror))

**Comment by mariopries** [comment]
same here

![image](https://github.com/Diizzayy/nuxt-graphql-client/assets/25091777/103e75ff-7326-4888-866b-b1856c810bc5)

**Comment by m0nch1** [comment]
It seems to me that GqlError could be included in the dist in some way...
Nuxt Module Builder might be relevant too?

**Comment by m0nch1** [comment]
I made a PR to export the type

**Comment by Diizzayy** [comment]
@mariopries Thanks for taking the time to address this! Your fix has been merged into the latest release.
