### ISSUE TITLE
Allow the host and clientHost to be changed at runtime

### ISSUE THREAD

**Issue by 4ndre4s** [Diizzayy/nuxt-graphql-client#482]
### Your use case

To run the same version of a software on different environments (dev, qa, prod) without rebuilding, it would be very helpful if you could provide the configuration for the host and clientHost at runtime (startup). Currently, this happens at build time.

### The solution you'd like

Nuxt offers a way for that: https://nuxt.com/docs/guide/going-further/runtime-config#environment-variables

Instead of reading environment variables at build time, relay on runtimeConfig (by convention) on runtime.

### Additional information

maybe that is already possible and just not documented?

**Comment by Diizzayy** [comment]
@4ndre4s This can be achieved via the `useGqlHost` composable, more information here: https://nuxt-graphql-client.web.app/getting-started/composables#usegqlhost

**Comment by 4ndre4s** [comment]
Thanks for the hint! That does not seem to be the nuxt way, isn't it?
