### ISSUE TITLE
Warning: Could not access `graphql-client`.

### ISSUE THREAD

**Issue by michael-hillmann** [Diizzayy/nuxt-graphql-client#501]
### Environment

Nuxt project info:                                                                                                - Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@8.15.1
- Builder:          -
- User Config:      modules, formkit, i18n, sitemap, pinia, runtimeConfig, css, nitro, routeRules, compatibilityDate        
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.1, @nuxtjs/i18n@8.3.1, @pinia/nuxt@0.5.1, @nuxtjs/robots@4.0.1, @formkit/nuxt@1.6.5, nuxt-graphql-client@0.2.35, @nuxtjs/sitemap@5.3.5
- Build Modules:    -

### Describe the bug

I can't get rid of this warning:
![nuxt-graphql-warning](https://github.com/user-attachments/assets/322e159d-29d0-4604-96ca-160e5049cff7)

### Expected behaviour

Startup without warning

### Reproduction

My config is:

``` js
export default defineNuxtConfig({
  :
  runtimeConfig: {
    public: {
      'graphql-client': {
        clients: {
          default: {
            :
            # my host settings
          },
        },
        codegen: {
          silent: false,
        },
      },
      :
      # other public configs
    },

  },
  :
  # other server configs
})
```

### Additional context

System is working (as far as I can see); I'm just a little unsettled by this warning.

**Comment by 4ndre4s** [comment]
I encountered the same issue.

**Comment by alexardra** [comment]
This is the line that causes the warning:
https://github.com/Diizzayy/nuxt-graphql-client/blob/b512fa0670a10a24e658a108379263363892e2ac/src/runtime/plugin.ts#L16

Seems like `config?.["graphql-client"]` never worked on client side but with Nuxt 3.12 we now get a warning for this. 

Simple check for `process.server` could solve this easily.

**Comment by premdasvm** [comment]
I'm having the same issue, any solutions?
