### ISSUE TITLE
Expose all queries under single object?

### ISSUE THREAD

**Issue by rchl** [Diizzayy/nuxt-graphql-client#51]
I haven't used the module (disclaimer) but I've read the documentation and I though that if I'd use the module, I would probably prefer all generated APIs to be exposed under single object. For example `$gql.launches`.

Did you think about doing it that way? Would there be disadvantages to that (like tree shaking)?

**Comment by Diizzayy** [comment]
> Did you think about doing it that way?

@rchl Indeed, the auto import aspect of the generated functions derive from a single composable `useGql`. You can disable `autoImport` in the module config and simply resort to using `useGql().launches`

> Would there be disadvantages to that (like tree shaking)?

None whatsoever 👍

**Comment by rchl** [comment]
So then would it make sense to expose the result of `useGql()` as an auto-import?

**Comment by rchl** [comment]
I see. So it sounds like it should be pretty easy to do something like that with some custom code, even if not that might require a manual import.
