### ISSUE TITLE
Generate API from different URL

### ISSUE THREAD

**Issue by rchl** [Diizzayy/nuxt-graphql-client#53]
My production GQL API doesn't have introspection enabled so I would guess that the module wouldn't be able to generate schema for it. I do have a stage API that does have introspection enabled though.

Would it make sense to be able to specify a different endpoint for generation and different endpoint to actually use for making queries? That would be one way to fix that problem, I guess.

Disclaimer: I'm not currently using this module (or event Nuxt 3) so this is just something I'm filing in case I would potentially want to use it in the future.

**Comment by Diizzayy** [comment]
@rchl As is ( _and I've yet to update the documentation to reflect this_ ) this module currently offers a solution for this very issue in the form of allowing a GraphQL schema file to be specified solely for introspection. You can have a look at the PR for now [allow schema to be provided for code generation](#42)

> Would it make sense to be able to specify a different endpoint for generation and different endpoint to actually use for making queries?

This workaround is in fact feasible and could be implemented if need be, though getting a copy of the GraphQL schema and providing it to the module is the preferred solution in this scenario (more efficient as well)
