### ISSUE TITLE
Global access token not used on client-side navigation

### ISSUE THREAD

**Issue by narduin** [Diizzayy/nuxt-graphql-client#54]
Hello!

I've been experimenting with nuxt3 and directus using your module to call the graphql endpoint.
I have set up the .env like so:

```env
GQL_HOST="http://localhost:8055/graphql"
GQL_TOKEN="MY_TOKEN"
```
I then created my request files and asyncData fetching like in the docs:
```js
// pages/posts/index.vue

const { data } = await useAsyncData('posts', () => GqlPosts())
```
This works great!

However, when doing the same thing inside a dynamic route page, it seems like the access token is no longer used. I get an error 400. Adding `useGqlToken('MY_TOKEN')` resolves this but I guess it is not intended.

```js
// pages/posts/[slug].vue

useGqlToken('MY_TOKEN')
const { data } = await useAsyncData('post-' + UID, () => GqlUniquePost({
  slug: route.params.slug,
  }))
```

Am I doing something wrong? Thanks a lot!

**Comment by narduin** [comment]
Oh I understand, this is sane behaviour. I just realized that it's the same with non-dynamic routes actually.
Is it supposed to be resolved by using the variables inside runtimeConfig? I tried this but nothing changed:

```js
// nuxt.config.ts

  runtimeConfig: {
    public: {
      'graphql-client': {
        clients: {
          default: {
            host: 'http://localhost:8055/graphql',
            token: 'MY_TOKEN'
          }
        }
      }
    }
  }
```

@Diizzayy, I think it would be favorable but I'm not entirely sure as I plan to use `nuxt generate` when fully supported.
I would not want you to work on this if `nuxt generate` will not be supported!

**Comment by Diizzayy** [comment]
> Is it supposed to be resolved by using the variables inside runtimeConfig?

Not quite, manually adding the token to `runtimeConfig` is equivalent to using an env variable.

> I think it would be favorable but I'm not entirely sure as I plan to use nuxt generate when fully supported.
I would not want you to work on this if nuxt generate will not be supported!

Using `nuxt generate` would certainly get around this issue, though you'd still need to make client-side authenticated requests during development.

I think there is merit in adding the `retainToken` flag as a bypass for the current behavior. If anything, we can always revise this at a later point.
