### ISSUE TITLE
Unable to load template plugin matching 'typescript'

### ISSUE THREAD

**Issue by jmdmacapagal** [Diizzayy/nuxt-graphql-client#71]
hi im experiencing this error

![168545966-fd91ce22-fb03-4a6d-80e4-c158b68fe50d](https://user-images.githubusercontent.com/34160255/168547487-30b3202c-ced5-456e-b85e-4ce7d2afaa90.png)

steps to reproduce:
follow the quick start guide from the documentation

"nuxt-graphql-client": "0.0.28",
"graphql": "^16.5.0",
"nuxt": "3.0.0-rc.3"

**Comment by Diizzayy** [comment]
@jmdmacapagal This should be fixed in the latest released. Be sure to update to the latest version and give it another try.
