### ISSUE TITLE
documentation request - show how to reference result types

### ISSUE THREAD

**Issue by farin** [Diizzayy/nuxt-graphql-client#81]
Hi

although types are automatically imported 
it's not clear how to reference result types

in other words, I would like to explicitly use result type in child component props 
```
<script setup lang="ts">
defineProps<{
  launch: ....
}>()
</script>
```

**Comment by Diizzayy** [comment]
@farin The auto imported gql function can be leveraged as seen below.

```vue
<script lang="ts" setup>
type FooType = Awaited<ReturnType<typeof GqlLaunches>>
defineProps<FooType>()
</script>
```

You can also import the gql function directly from `#build/gql` to infer your types as needed
