### ISSUE TITLE
how to use cookie from request headers ?

### ISSUE THREAD

**Issue by cfab** [Diizzayy/nuxt-graphql-client#87]
Hello,
I'm trying to use wordpress with wp-graphql and I need to post some mutations from my nuxt front-end.
I'm using [wp-grapql-cors](https://github.com/funkhaus/wp-graphql-cors) to login and there is indeed a Set-Cookie in the response headers.
Using Postman, I can see the cookie and with authorization tab set to "inherit from parent", if I post a mutation to create a page for example,  it works. 
But within nuxt, I dont know how to configure "nuxt-grapql-client" in order to have something equivalent !
Any help or example, is welcome ! 
Thank you.
PS: Here is a working generated example code from postman using axios: 
```js
var axios = require('axios');
var data = JSON.stringify({
  query: `mutation createPost {
  createPost(input: {
    title: "A nice title"
    content: "some content",
    status: PUBLISH
    }) {
    clientMutationId
  }
}`,
  variables: {}
});

var config = {
  method: 'post',
  url: 'https://galpon.test/graphql',
  headers: { 
    'Content-Type': 'application/json', 
    'Cookie': 'wordpress_logged_in_0a80706747350ab2bd151dfb3be09ba4=test2%7C1654774457%7CaUXw73nZkYwr1uxZkZwjcRkYPYPkONqJgDqd2jRTP8c%7C04441e5096ef211a79ba62f83e5cf34e1c9cfeffeb9c1933877f6231dc71d0de'
  },
  data : data
};

axios(config)
.then(function (response) {
  console.log(JSON.stringify(response.data));
})
.catch(function (error) {
  console.log(error);
});

```

**Comment by cfab** [comment]
Thank you. This is great, but I cannot hard code the token.value as it will be different for each user when they login...

**Comment by douglasgusson** [comment]
Hello, I would like to know if there is a possibility to include other parameters in the headers through the client configuration, for cases where custom headers are needed to read the API schema.

Thanks in advance!

**Comment by Diizzayy** [comment]
> for cases where custom headers are needed to read the API schema

@douglasgusson I haven't yet provided a way for this to be added via nuxt config (_though a PR enabling this is on the horizon_), and from my understanding this is where it's required for your use-case ( reading the API schema ). 

might I ask what the GraphQL service that you're using is and what the necessary headers are?

However though custom headers can be added to requests via [the `useGqlHeaders` composable](https://nuxt-graphql-client.web.app/getting-started/composables/#usegqlheaders). 

`nuxt-app/app.vue`
```vue
<script lang="ts" setup>
// 'X-Custom-Header' will be applied to all subsequent requests
useGqlHeaders({
  'X-Custom-Header': 'Custom Header Value'
})

// The headers set above will be applied both on SSR, as well as when called on client
const { data } = await useAsyncData('starlink', () => GqlLaunches())
</script>
```

**Comment by douglasgusson** [comment]
Hello, @Diizzayy, thanks for the answer.

My application is multitenancy. So, when I make a request, is needed to put an special header to specify what tenant I want to download the API schema. So, I would be greatfull if you allow to put it on requests.  If you preffer, I can make a PR.

**Comment by Diizzayy** [comment]
> My application is multitenancy

@douglasgusson Okay I understand, Thank you for the explanation.

> If you preffer, I can make a PR

That would be great.

**Comment by cfab** [comment]
> @cfab If you can create a repo for your project, I'd be willing to help you setup everything. You can also reach out to me on Discord - Diizzayy#1964
> 

@Diizzayy Many thanks for your thorough answer, this is great support ! I'll let you know if I don't manage...
