### ISSUE TITLE
How to force graphql to trust SSL?

### ISSUE THREAD

**Issue by TomDo1234** [Diizzayy/nuxt-graphql-client#90]
Context: A subdomain of a Wordpress multisite we have has a staging site.

Wp Engine has a bug where it doesnt have proper SSL for deep nested subdomains 

A staging site of a subdomain is a subdomain of a subdomain and wpengine doesnt support that well yet.

This leads to graphql not working because it doesnt trust ssl

I need to at the moment use http instead of https.

How to fix it? How to set something like ssl : false?

**Comment by Diizzayy** [comment]
> How to fix it? How to set something like ssl : false?

@TomDo1234 Unfortunately, This isn't an aspect that this module currently addresses

> I need to at the moment use http instead of https.

Strictly using an `http` url should suffice, providing that your server doesn't enforce / redirect requests to `https`
